### ISSUE TITLE
这么修改可提高并发

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [ydzydzydz/ssl-check#1]
大佬牛逼，代码还可以改进下，添加下图三个地方，可以提高并发。
本来想fork一个提合并请求的，不过好像东西不多，还搞的复杂了，就提个issue给你说了。

![image](https://user-images.githubusercontent.com/19485237/164970483-68a56a07-5b2f-4392-9b3e-2b10033e2975.png)

**Comment by ydzydzydz** [comment]
https://github.com/ydzydzydz/ssl-check/commit/1e77935302ff8cbb53e53c443c845236a191b076
